config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :profile_new
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :profiles, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :room
  belongs_to :user
  
  validates :room_id, presence: true
  validates :user_id, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :guest, class_name: 'User'
  has_many :comments
  has_many :comments_user, class_name: 'User', through: :comments, source: :user

  validates :user_id, presence: true
  validates :guest_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationship, source: :user
  
  has_one :profile
  
  has_many :rooms
  has_many :guests, through: :rooms, source: :guest
  has_many :reverse_of_rooms, class_name: 'Room', foreign_key: 'guest_id'
  has_many :hosts, through: :reverse_of_rooms, source: :user
  
  has_many :comments
  has_many :comments_room, class_name: 'Room', through: :comments, source: :room
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def matches
    followings & followers
  end
  
  def open_room(guest)
    unless self == guest
      self.rooms.create(guest_id: guest.id)
    end
  end
  
  def send_comment(room, content)
    self.comments.create(room_id: room.id, content: content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @comment = current_user.send_comment(@room, params[:comment][:content])
    
    if @comment.save
      flash[:success] = 'メッセージの送信に成功しました'
      redirect_to @room
    else
      flash[:danger] = 'メッセージの投稿に失敗しました'
      redirect_to @room
    end
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      flash[:success] = 'プロフィールが正常に作成されました。'
      redirect_to current_user
    else
      flash.now[:danger] = 'プロフィールの作成に失敗しました。'
    　render :new
    end
  end

  private
  
  def profile_params
    params.require(:profile).permit(:age, :job, :hobby, :comment, :sex)
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザーをフォローしました'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:succes] = 'ユーザーのフォローを解除しました'
    redirect_to user
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_user_logged_in
  before_action :require_user_matches, only: [:show]
  
  def create
    user = User.find(params[:guest_id])
    @room = current_user.open_room(user)
    if @room.save
      flash[:success] = 'ルームを作成しました'
      redirect_to @room
    else
      flash.now[:danger] = 'ルームの作成に失敗しました。'
      redirect_to user_path(current_user)
    end
  end
  
  def show
    @comments = Comment.where(room_id: params[:id])
  end
  
  private
  def require_user_matches
    @room = Room.find(params[:id])
    unless @room.user_id == current_user.id || @room.guest_id == current_user.id
      redirect_to user_path(current_user)
    end
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:sessions][:email].downcase
    passwoord = params[:sessions][:passwoord]
    
    if login(email, passwoord)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
    
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @users = User.all.page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, except: [:new, :create]
  before_action :profile_check, only: [:profile_new]
  before_action :user_check, only: [:profile_new]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @users = @user.matches
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  
  def profile_new
    @profile = current_user.build_profile
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def profile_check
    @profile = Profile.find_by(user_id: current_user.id)
    if @profile
      redirect_to user_path(current_user)
    end
    
    def user_check
      @user = User.find(params[:id])
      unless @user = current_user
        redirect_to user_path(current_user)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size:80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
  <p><%= comment.user.name %>:<%= comment.content %></p>
<% end %>

<%= form_for(current_user.comments.create) do |f| %>
  <%= hidden_field_tag :room_id, params[:id] %>
  <div class="form-group">
    <%= f.label :content, 'メッセージ' %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <%= f.submit 'メッセージを送る', class: 'btn btn-success' %>
<% end %>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete}) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'いいねを外す', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'いいね！', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/rooms/_room_button.html.erb
<% unless current_user == user %>
  <% if Room.find_by(user_id: current_user.id, guest_id: user.id) then %>
    <% room = Room.find_by(user_id: current_user.id, guest_id: user.id) %>
    <%= link_to 'メッセージ', room_path(room), class: 'btn btn-success' %>
  <% elsif Room.find_by(user_id: user.id, guest_id: current_user.id) then %>
    <% room =  Room.find_by(user_id: user.id, guest_id: current_user.id) %>
    <%= link_to 'メッセージ', room_path(room), class: 'btn btn-success' %>
  <% else %>
    <%= form_for(current_user.rooms.create) do |f| %>
      <%= hidden_field_tag :guest_id, user.id %>
      <%= f.submit 'メッセージ', class: 'btn btn-success' %>
    <% end %>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<h1 class="text-center">メッセージルーム</h1>
<%= render 'comments/comments', comments: @comments %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <% content_for :cover do %>
    <div class="cover"></div>
  <% end %>
  <div class="text-center">
    <h3>素敵な出会いをしよう</h3>
  </div>
  <%= render 'users/users', users: @users %>
<% else %>
  <% content_for :cover do %>
    <div class="cover"></div>
  <% end %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>マッチングアプリへようこそ！</h1>
      <%= link_to '会員登録する', signup_path, class: 'btn btn-primary' %>
      <%= link_to 'ログインする', login_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="text-center">
    <h3>素敵な出会いをしよう</h3>
  </div>
  <%= render 'users/users', users: @users %>
<% end %>

app/views/users/_users.html.erb
<% if users %>
  <div class="row">
    <% users.each do |user| %>
      <div class="user">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= gravatar_url(user, { size: 250 }) %>" alt="" class="img-circle">
            </div>
            <div class="panel-body">
              <p class="user-title" align="center"><%= link_to user.name, user_path(user) %></p>
              <% if logged_in? %>
                <div class="buttons text-center">
                  <%= render 'relationships/follow_button', user: user %>
                  <% if Relationship.find_by(user_id: current_user.id, follow_id: user.id) && Relationship.find_by(user_id: user.id, follow_id: current_user.id) %>
                    <%= render 'rooms/room_button', user: user %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="user">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <img src="<%= gravatar_url(@user, { size: 250 }) %>" alt="" class="img-circle">
        </div>
        <div class="panel-body">
          <p class="user-title" align="center"><%= @user.name %></p>
        </div>
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <h2><%= @user.name %>さんのプロフィール</h2>
    <% if Profile.exists?(user_id: @user.id) %>
      <table class="table">
        <tr>
          <td class="text-left">ご年齢</td>
        　<td class="text-left"><%= @user.profile.age %></td>
        </tr>
        <tr>
          <td class="text-left">性別</td>
          <td class="text-left"><%= @user.profile.sex %></td>
        </tr>
        <tr>
          <td class="text-left">ご職業</td>
          <td class="text-left"><%= @user.profile.job %></td>
        </tr>
        <tr>
          <td class="text-left">ご趣味</td>
          <td class="text-left"><%= @user.profile.hobby %></td>
        </tr>
        <tr>
          <td class="text-left">ひとこと</td>
          <td class="text-left"><%= @user.profile.comment %></td>
        </tr>
      </table>
    <% else %>
      <% if current_user == @user %>
        <%= link_to 'プロフィールを作成する', profile_new_user_path %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row">
  <ul class="nav nav-jastified nav-tabs">
    <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>マッチング済み<% end %></li>
    <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>いいねしているユーザー<% end %></li>
    <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>いいねされているユーザー<% end %></li>
  </ul>
    <%= render 'users/users', users: @users %>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="user">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <img src="<%= gravatar_url(@user, { size: 250 }) %>" alt="" class="img-circle">
        </div>
        <div class="panel-body">
          <p class="user-title" align="center"><%= @user.name %></p>
        </div>
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <h2><%= @user.name %>さんのプロフィール</h2>
    <% if Profile.exists?(user_id: @user.id) %>
      <table class="table">
        <tr>
          <td class="text-left">ご年齢</td>
        　<td class="text-left"><%= @user.profile.age %></td>
        </tr>
        <tr>
          <td class="text-left">性別</td>
          <td class="text-left"><%=@user.profile.sex %></td>
        </tr>
        <tr>
          <td class="text-left">ご職業</td>
          <td class="text-left"><%= @user.profile.job %></td>
        </tr>
        <tr>
          <td class="text-left">ご趣味</td>
          <td class="text-left"><%= @user.profile.hobby %></td>
        </tr>
        <tr>
          <td class="text-left">ひとこと</td>
          <td class="text-left"><%= @user.profile.comment %></td>
        </tr>
      </table>
    <% else %> 
      <% if current_user == @user %>
        <%= link_to 'プロフィールを作成する', profile_new_user_path %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row">
  <ul class="nav nav-jastified nav-tabs">
    <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>マッチング済み<% end %></li>
    <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>いいねしてるユーザー<% end %></li>
    <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>いいねされているユーザー<% end %></li>
  </ul>
    <%= render 'users/users', users: @users %>
</div>

app/views/users/index.html.erb
<div class="text-center"><h1>ユーザー一覧ページ</h1></div>

<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user)do |f| %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :passwoord, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit '登録する', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/profile_new.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
  <h1>プロフィールを作る</h1>
    <%= form_for(@profile) do |f| %>
      <div class="form-group">
        <%= f.label :age, 'ご年齢' %>
        <%= f.text_field :age, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :sex, '性別' %>
        <%= f.text_field :sex, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :job, 'ご職業' %>
        <%= f.text_field :job, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :hobby, 'ご趣味' %>
        <%= f.text_field :hobby, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :comment, 'ひとこと' %>
        <%= f.text_field :comment, class: 'form-control' %>
      </div>
      <%= f.submit '作成！', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="user">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <img src="<%= gravatar_url(@user, { size: 250 }) %>" alt="" class="img-circle">
        </div>
        <div class="panel-body">
          <p class="user-title"><%= @user.name %></p>
        </div>
      </div>
    </div>
  </aside>
</div>