config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :profile_new
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :profiles, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :room
  belongs_to :user
  
  validates :room_id, presence: true
  validates :user_id, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :guest, class_name: 'User'
  has_many :comments
  has_many :comments_user, class_name: 'User', through: :comments, source: :user

  validates :user_id, presence: true
  validates :guest_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationship, source: :user
  
  has_one :profile
  
  has_many :rooms
  has_many :guests, through: :rooms, source: :guest
  has_many :reverse_of_rooms, class_name: 'Room', foreign_key: 'guest_id'
  has_many :hosts, through: :reverse_of_rooms, source: :user
  
  has_many :comments
  has_many :comments_room, class_name: 'Room', through: :comments, source: :room
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def matches
    followings & followers
  end
  
  def open_room(guest)
    unless self == guest
      self.rooms.create(guest_id: guest.id)
    end
  end
  
  def send_comment(room, content)
    self.comments.create(room_id: room.id, content: content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @comment = current_user.send_comment(@room, params[:comment][:content])
    
    if @comment.save
      flash[:success] = 'メッセージの送信に成功しました'
      redirect_to @room
    else
      flash[:danger] = 'メッセージの投稿に失敗しました'
      redirect_to @room
    end
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      flash[:success] = 'プロフィールが正常に作成されました。'
      redirect_to current_user
    else
      flash.now[:danger] = 'プロフィールの作成に失敗しました。'
    　render :new
    end
  end

  private
  
  def profile_params
    params.require(:profile).permit(:age, :job, :hobby, :comment, :sex)
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_user_logged_in
  before_action :require_user_matches, only: [:show]
  
  def create
    user = User.find(params[:guest_id])
    @room = current_user.open_room(user)
    if @room.save
      flash[:success] = 'ルームを作成しました'
      redirect_to @room
    else
      flash.now[:danger] = 'ルームの作成に失敗しました。'
      redirect_to user_path(current_user)
    end
  end
  
  def show
    @comments = Comment.where(room_id: params[:id])
  end
  
  private
  def require_user_matches
    @room = Room.find(params[:id])
    unless @room.user_id == current_user.id || @room.guest_id == current_user.id
      redirect_to user_path(current_user)
    end
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:sessions][:email].downcase
    passwoord = params[:sessions][:passwoord]
    
    if login(email, passwoord)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
    
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @users = User.all.page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, except: [:new, :create]
  before_action :profile_check, only: [:profile_new]
  before_action :user_check, only: [:profile_new]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @users = @user.matches
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  
  def profile_new
    @profile = current_user.build_profile
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def profile_check
    @profile = Profile.find_by(user_id: current_user.id)
    if @profile
      redirect_to user_path(current_user)
    end
    
    def user_check
      @user = User.find(params[:id])
      unless @user = current_user
        redirect_to user_path(current_user)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size:80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type =%>">
    <%= message =%>
  </div>
<% end %>
    
  

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle nvigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Matching</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'ユーザー一覧', users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt"" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'マイページ', user_path(current_user) %></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '会員登録', new_user_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Matching</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <%= yield :cover %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

    <%= yield %>
    </div>
  </body>
</html>